import type { Metadata } from 'next'

import './globals.css'
import styles from './layout.module.scss'

import Navigation from '@/layout/navigation/navigation'
import Sidebar from '@/layout/sidebar/sidebar'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <div className={styles.layout}>
          <Navigation />
          <div className={styles.center}>{children}</div>
          <Sidebar />
        </div>
      </body>
    </html>
  )
}
